run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/regstrava/regstrava
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: cmd/
      linters:
        - unparam
  max-issues-per-linter: 50
  max-same-issues: 10
